spring:
  profiles:
    active: dev   # dev profile? ??
  application:
    name: user-service
  config:
    import: configserver:${CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      profile: dev    # dev profile ?? ?? ??
      label: main
