apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}     # Ingress의 Service Name과 매치
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}    # Deployment Pod 찾기