replicaCount: 1

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
  tag: 20250527-ce68e96
  pullPolicy: IfNotPresent    # 이미지 가져오는 정책 로컬에 없을 때만 pull

service:
  type: ClusterIP   # 클러스터 내부에서만 접근 가능 (기본값)
  port: 80

# 헬스체크 설정 (권장)
healthCheck:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

# User Service Config
config:
  server:
    port: 8080
  app:
    name: user-service
  jpa:
    hibernate:
      ddlauto: ddl-update
  datasource:
    driverclassname: com.mysql.cj.jdbc.Driver